/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#902d13",
        "primary-container": "#b14529",
        "primary-fixed": "#ffdbd2",
        "primary-fixed-dim": "#ffb4a2",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#3c0800",
        "on-primary-fixed-variant": "#84250b",
        "on-primary-container": "#ffe1da",
        "inverse-primary": "#ffb4a2",

        secondary: "#795900",
        "secondary-container": "#fcc340",
        "secondary-fixed": "#ffdea0",
        "secondary-fixed-dim": "#f6be3b",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#261900",
        "on-secondary-fixed-variant": "#5c4300",
        "on-secondary-container": "#6f5100",

        tertiary: "#67483f",
        "tertiary-container": "#816056",
        "tertiary-fixed": "#ffdbd0",
        "tertiary-fixed-dim": "#e7bdb1",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#2c160e",
        "on-tertiary-fixed-variant": "#5d4037",
        "on-tertiary-container": "#ffe1d8",

        surface: "#fbf9f5",
        "surface-dim": "#dbdad6",
        "surface-bright": "#fbf9f5",
        "surface-variant": "#e4e2de",
        "surface-tint": "#a53c21",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3ef",
        "surface-container": "#efeeea",
        "surface-container-high": "#eae8e4",
        "surface-container-highest": "#e4e2de",
        "on-surface": "#1b1c1a",
        "on-surface-variant": "#54433c",
        "inverse-surface": "#30312e",
        "inverse-on-surface": "#f2f0ed",

        background: "#fbf9f5",
        "on-background": "#1b1c1a",

        outline: "#87736b",
        "outline-variant": "#dac1b8",

        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        headline: ["PlusJakartaSans_700Bold"],
        "headline-extra": ["PlusJakartaSans_800ExtraBold"],
        body: ["BeVietnamPro_400Regular"],
        "body-medium": ["BeVietnamPro_500Medium"],
        "body-semibold": ["BeVietnamPro_600SemiBold"],
        label: ["BeVietnamPro_600SemiBold"],
      },
      borderRadius: {
        DEFAULT: "4px",
        lg: "8px",
        xl: "12px",
        "2xl": "16px",
        "3xl": "24px",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
